-keep class io.netty.** { *; }
-dontwarn io.netty.**
-keep class org.cloudburstmc.** { *; }
-dontwarn org.cloudburstmc.**
-keep class com.microsoft.identity.** { *; }
-dontwarn com.microsoft.identity.**
-keep class com.oxclient.** { *; }
-keepattributes SourceFile,LineNumberTable,*Annotation*,Signature,InnerClasses
-renamesourcefileattribute SourceFile
-keep class com.google.gson.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
